name: PanIndex Release
on:
  release:
    types: [created]
jobs:
  release:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.20.1]
    name: PanIndex Release
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: main
      - name: Build PanIndex
        uses: libsgh/PanIndex-build-action@main
        with:
          type: "release_build"
          go-version: ${{ matrix.go-version }}
          artifact-name: "Actions-Test"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: /home/runner/work/PanIndex/PanIndex/dist/compress/*