name: PanIndex Nightly Docker Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_docker:
    if: contains('["libsgh"]', github.actor)
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: main
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: iicm/actions-test
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: iicm
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ github.ref }}
            ARG0=nightly_docker
          tags: iicm/actions-test:dev
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
          cache-from: type=registry,ref=iicm/actions-test:dev
          cache-to: type=inline