name: Release Build
on:
  release:
    types: [created]
jobs:
  build:
    strategy:
      matrix:
        type: [build, build_musl]
        platform: [ubuntu-latest]
        go-version: [1.20.1]
    name: Release and Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: main
      - name: Build
        uses: libsgh/go-build-action@main
        with:
          type:  ${{ matrix.type }}
          go-version: ${{ matrix.go-version }}
          artifact-name: "Actions-Test"
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Compress
        run: |
          ls -n ${{github.workspace}}/dist
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{github.workspace}}/dist/compress/*

